server:
  port: 8081
  mvc:
    pathmatching-strategy: ANT_PATH_MATCHER
spring:
  application:
    name: passagem-service
  datasource:
    url: jdbc:postgresql://localhost:5432/companhia_aerea
    driverClassName:
    username: microservices
    password: 123456
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: "Initial schema"
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql